Document: supreme
Title: Debian supreme Manual
Author: <insert document author here>
Abstract: This manual describes what supreme is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/supreme/supreme.sgml.gz

Format: postscript
Files: /usr/share/doc/supreme/supreme.ps.gz

Format: text
Files: /usr/share/doc/supreme/supreme.text.gz

Format: HTML
Index: /usr/share/doc/supreme/html/index.html
Files: /usr/share/doc/supreme/html/*.html
