#!/bin/bash
#kiran.vkvr@gmail.com
#https://github.com/Kiran-Bose/supreme

#------------------------------------------------------------------------------------------------
function kbbar ()
{
user=$(whoami)
ptghistory=()
loopchk=()
local i
local barcols=$(tput cols)
local LENGTH=$(($barcols-8))
local REMAINING="\e[107m \e[0m"
local COMPLETED="\e[42m \e[0m"
tots=$3
IFS=$(echo -en "\n\b")
if [ "$1" == "$2" ] || [ "$tots" == 0 ]
then
return
fi
if [[ ! -d "$2" ]] || [[ ! -f "$2" ]]
then
sleep 1
fi
if [[ (-d "$2") || (-f "$2") ]] && [[ (-d "$1") || (-f "$1") ]] && [[ $tots != 0 ]]
then
chk1=$(echo "$1" | rev | cut -d/ -f2- | rev )
chk2=$(echo "$2" | rev | cut -d/ -f2- | rev )
fs1=$(df "$chk1" | awk '{print $1}' | sed 1d)
fs2=$(df "$chk2" | awk '{print $1}' | sed 1d)
	if [[ ("$fs1" == "$fs2") && ($qbar == 0) ]]
	then
	return
	else
	sptg=0
	totd=0
	arraysz1=()
	ptg=0
	ss=$tots
	bypass=$(sudo whoami)
	echo -en "\e[44;97;10;82m  0%  \e[0m "
		for i in `seq 1 $LENGTH`
		do
		echo -en "$REMAINING"
		done
	while echo "($ptg < 99)" | bc | grep -q 1
	do
	totd=0
	local barcols=$(tput cols)
	local LENGTH=$(($barcols-8))	
		if [[ (-d "$1") || (-f "$1") ]]
		then
		loopchk+=($ptg)
			if [[ (-d "$2") || (-f "$2") ]]
			then
			loopchk=()
				if [[ "$2" == *"/$UID/gvfs/mtp"* ]]
				then
				IFS=$'\n' read -rd '' -a arraysz1 <<< `ls -Ral "$2" | awk '{print $5}' | sed 's/[^0-9]*//g'` 
				else
				IFS=$'\n' read -rd '' -a arraysz1 <<< `sudo ls -Ral "$2" | awk '{print $5}' | sed 's/[^0-9]*//g'` 
				fi
				for ((i=0; i<${#arraysz1[@]}; i++)); do
				totd=$(($totd + "${arraysz1[$i]}"))	
				done
			echo -en "\0015"
			ds=$totd
			ptg=$( echo "scale=6; $ds/$ss * 100" | bc )
			sptg=${ptg%.*}
			clb=$( echo "scale=6; $ptg/100 * $LENGTH" | bc )
			ptghistory+=($sptg)
				if(($sptg>100)) > /dev/null 2>&1
				then
				echo -en "\e[44;97;10;82m 100% \e[0m\e[89m \e[0m"
					for i in `seq 1 $LENGTH`
					do
					echo -en "$COMPLETED"
					done
					echo -e "\n"
				return
				else
					if((${#ptghistory[@]}>100)) > /dev/null 2>&1
					then
						if [[ $(pgrep -xn cp) || $(pgrep -xn mv) ]]
						then
						ptghistory=()
						else
						echo -en "\e[44;97;10;82m 100% \e[0m\e[89m \e[0m"
							for i in `seq 1 $LENGTH`
							do
							echo -en "$COMPLETED"
							done
							echo -e "\n"
						return 1
						fi
					fi
				fi
			local EMPTY=$( echo "scale=6; $LENGTH-$clb" | bc )	
			echo -en "\e[44;97;10;82m  $sptg% \e[0m\e[89m \e[0m"
				for i in `seq 1 $clb`
				do
				echo -en "$COMPLETED"
				done
				for i in `seq 1 $EMPTY`
				do
				echo -en "$REMAINING"
				done
			else
			echo
			echo -e "\e[91mTransfer error/Device disconnected\e[0m"
			return 1
			fi
			if((${#loopchk[@]}>100)) > /dev/null 2>&1
			then
			return 1
			fi
		else
		sleep 1
			if [[ (-d "$2") || (-f "$2") ]]
			then
			totd=0
			local barcols=$(tput cols)
			local LENGTH=$(($barcols-8))
				if [[ "$2" == *"/$UID/gvfs/mtp"* ]]
				then
				IFS=$'\n' read -rd '' -a arraysz1 <<< `ls -Ral "$2" | awk '{print $5}' | sed 's/[^0-9]*//g'` 
				else
				IFS=$'\n' read -rd '' -a arraysz1 <<< `sudo ls -Ral "$2" | awk '{print $5}' | sed 's/[^0-9]*//g'` 
				fi
				for ((i=0; i<${#arraysz1[@]}; i++)); do
				totd=$(($totd + "${arraysz1[$i]}"))	
				done
			ds=$totd
			ptg=$( echo "scale=6; $ds/$ss * 100" | bc )
			fi
		break
		fi
	#sleep 0.18
	done
		if echo "($ptg > 99)" | bc | grep -q 1
		then
		echo -en "\0015"
		echo -en "\e[44;97;10;82m 100% \e[0m\e[89m \e[0m"
			for i in `seq 1 $LENGTH`
			do
			echo -en "$COMPLETED"
			done
			echo -e "\n"
		else
		echo -e "\n"
		fi
	fi
fi
}

#------------------------------------------------------------------------------------------------

